### PR TITLE
Enable flake update auto-merge and clean up flake.nix

### PR DESCRIPTION
**Pull request by szg251**
- Allow auto-merge of flake-updates
- Update flake

### CODE REVIEW

**Comment by szg251** [comment]
@jaredponn For some reason flake-updates stopped working on this repo, do you have any clue why this could happen?

**Comment by jaredponn** [comment]
> @jaredponn For some reason flake-updates stopped working on this repo, do you have any clue why this could happen?

Sorry, I don't have any idea why this could happen.

Also,  #25 was quite broken -- sorry if you spent a bunch of time trying to get it to work.

**Review by bladyjoker — APPROVED** [review]
Remind me please: is this now a circular Nix dep? LB flake input is pla-rust, pla-rust flake input is LB?

**Comment by szg251** [comment]
> Remind me please: is this now a circular Nix dep? LB flake input is pla-rust, pla-rust flake input is LB?

Oh sht, you are right...

**Review by jaredponn — APPROVED** [review]
Nice!

If we ever get around to removing the cyclic dependency with LB and this, that'd be really great :). Helps reduce lock file sizes and reduces time spent waiting for nix :P

**Pull request merged**
